# Generated by Django 4.2.2 on 2023-06-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_resume"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill", models.CharField(blank=True, max_length=100, null=True)),
                ("level", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
