# Generated by Django 4.2.2 on 2023-06-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_skills"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about_skill",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "about_service",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
            ],
        ),
    ]
