# Generated by Django 4.2.2 on 2023-06-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_skillservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("phone", models.CharField(blank=True, max_length=13, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("message", models.TextField(max_length=2000, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
