# Generated by Django 4.2.2 on 2023-06-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "service_css_class",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="visit https://themify.me/themify-icons",
                    ),
                ),
            ],
        ),
    ]
