# Generated by Django 4.2.2 on 2023-06-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_portfolio_description_alter_portfolio_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Maps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "map",
                    models.CharField(
                        max_length=100,
                        null=True,
                        verbose_name="Enter address, to confirm if it is avaible visit: https://embed-googlemap.com/",
                    ),
                ),
            ],
        ),
    ]
