# Generated by Django 4.2.2 on 2023-06-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_profile_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="tagline",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
