# Generated by Django 4.2.2 on 2024-02-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_portfolio_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.URLField(max_length=1000),
        ),
    ]
